Keras_Tuner:
  dim: !!python/tuple [128, 128]
  dataset: JAAD_dataset
  path_instances: /pub/experiments/jzafra/instances/JAAD_pedestrians
  path_train_id_instances: /pub/experiments/jzafra/ids_instances/JAAD/train.txt
  path_validation_id_instances: /pub/experiments/jzafra/ids_instances/JAAD/validation.txt
  path_test_id_instances: /pub/experiments/jzafra/ids_instances/JAAD/test.txt
  path_dir_results: /pub/experiments/jzafra/
  epochs: 100
  n_frames: 8
  seed: 1
  num_classes: 2
  random: False
  tuners:
    tuner_1:
      type: Bayesian_Optimization
      objetive: val_accuracy
      seed: 1
      num_initial_points: 5
      max_trials: 100
      directory: /pub/experiments/jzafra/tuner_keras_results/JAAD_dataset/hypertuners/Bayesian_Optimization
      project_name: CONV3D_model



