Hyperparameters_Optimization_Shuffle:
  n_frames: 16
  dim: !!python/tuple [ 128, 128 ]
  n_channels: 3
  dataset: 'PIE_dataset'
  type_model: 'CONV3D'
  data_sampling: 'OpticalFlow' # Distributed
  path_instances: '/pub/experiments/jzafra/instances/'              # '/media/jorge/DATOS/TFG/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'       # '/media/jorge/DATOS/TFG/ids_instances/'
  path_dir_results: '/pub/experiments/jzafra/tuner_keras_results'   # '/media/jorge/DATOS/TFG/tuner_keras_results'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters'   # '/media/jorge/DATOS/TFG/hyperparameters'
  epochs: 100
  seed: 1
  random: False
  tuner:
    type: 'Bayesian_Optimization'
    objetive: val_loss
    seed: 1
    executions_per_trial: 2           #Random_Search, HyperBand
    max_trials: 100                   #Random_Search, Bayesian_Optimization
    max_epochs: 100                   #HyperBand
    num_initial_points: 5             #Bayesian_Optimization
    project_name: '03112020-184600'
Hyperparameters_Optimization_OrderPrediction:
  dim: !!python/tuple [ 128, 128 ]
  n_channels: 3
  dataset: 'PIE_dataset'
  type_model: 'SIAMESE'
  data_sampling: 'Distributed' # Distributed OpticalFlow
  path_instances: '/pub/experiments/jzafra/instances/'              #'/media/jorge/DATOS/TFG/instances/'             
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'       #'/media/jorge/DATOS/TFG/ids_instances/'        
  path_dir_results: '/pub/experiments/jzafra/tuner_keras_results'   #'/media/jorge/DATOS/TFG/tuner_keras_results'    
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters'   #'/media/jorge/DATOS/TFG/hyperparameters'    
  epochs: 100
  seed: 1
  random: False
  tuner:
    type: 'Bayesian_Optimization'
    objetive: val_loss
    seed: 1
    executions_per_trial: 2           #Random_Search, HyperBand
    max_trials: 100                   #Random_Search, Bayesian_Optimization
    max_epochs: 100                   #HyperBand
    num_initial_points: 5             #Bayesian_Optimization
    project_name: '06112020-172000'
Shuffle:
  n_frames: 16
  dim: !!python/tuple [128, 128]
  n_channels: 3
  dataset: 'PIE_dataset'
  type_model: 'CONV3D'
  data_sampling: 'OpticalFlow'
  tuner_type: 'Bayesian_Optimization' #Random_Search, Manual, ...
  project_name: '03112020-184600'
  path_instances: '/pub/experiments/jzafra/instances/'              #'/media/jorge/DATOS/TFG/instances/'             
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'       #'/media/jorge/DATOS/TFG/ids_instances/'      
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/'  #'/media/jorge/DATOS/TFG/hyperparameters/'
  tensorboard_logs: '/pub/experiments/jzafra/tensorboard/'          #'/media/jorge/DATOS/TFG/tensorboard/'   
  path_output_model: '/pub/experiments/jzafra/models/'              #'/media/jorge/DATOS/TFG/models/'             
  epochs: 100
  seed: 1
  random: False
OrderPrediction:
  dim: !!python/tuple [128, 128]
  n_channels: 3
  dataset: 'PIE_dataset'
  type_model: 'SIAMESE'
  data_sampling: 'Distributed'
  tuner_type: 'Bayesian_Optimization' #Random_Search, Manual, ...
  project_name: '06112020-172000'
  path_instances: '/pub/experiments/jzafra/instances/'              #'/pub/experiments/jzafra/instances/'         '/media/jorge/DATOS/TFG/instances/'  
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'       #'/pub/experiments/jzafra/ids_instances/'     '/media/jorge/DATOS/TFG/ids_instances/'     
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/'  #'/pub/experiments/jzafra/hyperparameters/'   '/media/jorge/DATOS/TFG/hyperparameters/'
  tensorboard_logs: '/pub/experiments/jzafra/tensorboard/'          #'/pub/experiments/jzafra/tensorboard/'       '/media/jorge/DATOS/TFG/tensorboard/'
  path_output_model: '/pub/experiments/jzafra/models/'              #'/pub/experiments/jzafra/models/'            '/media/jorge/DATOS/TFG/models/'
  epochs: 100
  seed: 1
  random: False
HP_Optimization_CrossingDetection_Shuffle:
  n_frames: 16
  dim: !!python/tuple [ 128, 128 ]
  n_channels: 3
  dataset: 'PIE_dataset'
  type_model: 'CONV3D'
  data_sampling: 'OpticalFlow' # OpticalFlow
  Transfer_Learning: False
  path_instances: '/pub/experiments/jzafra/instances/' #'/media/jorge/DATOS/TFG/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/' #'/media/jorge/DATOS/TFG/ids_instances/'
  path_dir_results: '/pub/experiments/jzafra/tuner_keras_results/' #'/media/jorge/DATOS/TFG/tuner_keras_results'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/' #'/media/jorge/DATOS/TFG/hyperparameters'
  path_weights: '/pub/experiments/jzafra/models/'
  tuner_type_pretext_task: 'Bayesian_Optimization'
  project_name_pretext_task: '03112020-184600'
  epochs: 100
  seed: 1
  random: False
  tuner:
    type: 'Bayesian_Optimization'
    objetive: val_loss
    seed: 1
    executions_per_trial: 2           #Random_Search, HyperBand
    max_trials: 100                   #Random_Search, Bayesian_Optimization
    max_epochs: 100                   #HyperBand
    num_initial_points: 5             #Bayesian_Optimization
    project_name: '03112020-184600'
HP_Optimization_CrossingDetection_OrderPrediction:
  dim: !!python/tuple [ 128, 128 ]
  n_channels: 3
  dataset: 'PIE_dataset'
  type_model: 'SIAMESE'
  data_sampling: 'Distributed' # OpticalFlow
  Transfer_Learning: False
  path_instances: '/pub/experiments/jzafra/instances/' #'/media/jorge/DATOS/TFG/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/' #'/media/jorge/DATOS/TFG/ids_instances/'
  path_dir_results: '/pub/experiments/jzafra/tuner_keras_results/' #'/media/jorge/DATOS/TFG/tuner_keras_results'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/' #'/media/jorge/DATOS/TFG/hyperparameters'
  path_weights: '/pub/experiments/jzafra/models/'
  tuner_type_pretext_task: '' #'Bayesian_Optimization'
  project_name_pretext_task: '' #'06112020-172000'
  epochs: 100
  seed: 1
  random: False
  tuner:
    type: 'Bayesian_Optimization'
    objetive: val_loss
    seed: 1
    executions_per_trial: 2           #Random_Search, HyperBand
    max_trials: 100                   #Random_Search, Bayesian_Optimization
    max_epochs: 100                   #HyperBand
    num_initial_points: 5             #Bayesian_Optimization
    project_name: '07112020-172000'
CrossingDetection_Shuffle:
  n_frames: 16
  dim: !!python/tuple [ 128, 128 ]
  n_channels: 3
  dataset: 'PIE_dataset'
  type_model: 'CONV3D'
  data_sampling: 'OpticalFlow' # OpticalFlow
  project_name: '03112020-184600'
  tuner_type: 'Bayesian_Optimization'
  Transfer_Learning: True
  path_weights: '/pub/experiments/jzafra/models/'
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  tensorboard_logs: '/pub/experiments/jzafra/tensorboard/'
  path_output_model: '/pub/experiments/jzafra/models/'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/'
  tuner_type_pretext_task: 'Bayesian_Optimization'
  project_name_pretext_task: '06112020-172000'
  epochs: 100
  seed: 1
  random: False
CrossingDetection_OrderPrediction:
  dim: !!python/tuple [ 128, 128 ]
  n_channels: 3
  dataset: 'PIE_dataset'
  type_model: 'SIAMESE'
  data_sampling: 'Distributed' # OpticalFlow
  project_name: '07112020-172000'
  tuner_type: 'Bayesian_Optimization'
  Transfer_Learning: True
  path_weights: '/pub/experiments/jzafra/models/'
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  tensorboard_logs: '/pub/experiments/jzafra/tensorboard/'
  path_output_model: '/pub/experiments/jzafra/models/'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/'
  tuner_type_pretext_task: 'Bayesian_Optimization'
  project_name_pretext_task: '06112020-172000'
  epochs: 100
  seed: 1
  random: False
Performance_CrossingDetection_Shuffle:
  n_frames: 16
  dim: !!python/tuple [128, 128]
  n_channels: 3
  dataset: 'PIE_dataset'
  data_sampling: 'OpticalFlow'
  Transfer_Learning: False
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/'
  path_weights: '/pub/experiments/jzafra/models/'
  type_model: 'CONV3D'
  project_name: '03112020-184600'
  tuner_type: 'Bayesian_Optimization'
  seed: 1
  random: False
Performance_CrossingDetection_OrderPrediction:
  dim: !!python/tuple [128, 128]
  n_channels: 3
  dataset: 'PIE_dataset'
  data_sampling: 'Distributed'
  Transfer_Learning: True
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/'
  path_weights: '/pub/experiments/jzafra/models/'
  type_model: 'SIAMESE'
  project_name: '07112020-172000'
  tuner_type: 'Bayesian_Optimization'
  seed: 1
  random: False


