Keras_Tuner:
  dim: !!python/tuple [128, 128]
  dataset: 'PIE_dataset'
  pretext_task: 'Shuffle'
  model: 'CONV3D'
  type_model: 'Crossing-detection'
  Transfer_Learning:
    activated: True
    path_weights_conv_layers: '/pub/experiments/jzafra/models/PIE_dataset/Shuffle/CONV3D/06092020-170054/weights.h5'
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  path_dir_results: '/pub/experiments/jzafra/tuner_keras_results'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters'
  epochs: 100
  n_frames: 16
  seed: 1
  num_classes: 2
  random: False
  tuner:
    type: 'Bayesian_Optimization'
    objetive: val_loss
    seed: 1
    num_initial_points: 5
    max_trials: 100
    project_name: '14092020-130900'
Shuffle:
  dim: !!python/tuple [128, 128]
  dataset: 'PIE_dataset'
  model_name: 'CONV3D'
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  epochs: 100
  n_frames: 16
  seed: 1
  random: False
  tensorboard_logs: '/pub/experiments/jzafra/tensorboard'
  path_output_model: '/pub/experiments/jzafra/models'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/PIE_dataset/Shuffle/Bayesian_Optimization/CONV3D/04092020-213100.json'
Transfer_Learning:
  dataset: 'PIE_dataset'
  pretext_task: 'Shuffle'
  model_name: 'CONV3D'
  input_model: '06092020-170054'
  type_model: 'Crossing-detection'
  path_weights: '/pub/experiments/jzafra/models'
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  tensorboard_logs: '/pub/experiments/jzafra/tensorboard'
  path_output_model: '/pub/experiments/jzafra/models'
  epochs: 100
  seed: 1
  random: False
  dim: !!python/tuple [128, 128]
  n_frames: 16
  n_classes: 2
  channels: 3
  batch_size: 32
  normalized: True
  shuffle: True
  path_hyperparameters_classification_layer: '/pub/experiments/jzafra/hyperparameters/PIE_dataset/Transfer_Learning/Shuffle/Bayesian_Optimization/CONV3D/Classification_Layer/14072020-165700.json'
  path_hyperparameters_fine_tuning: '/pub/experiments/jzafra/hyperparameters/PIE_dataset/Transfer_Learning/Shuffle/Bayesian_Optimization/CONV3D/Fine_Tuning/14072020-165700.json'



