Keras_Tuner:
  dim: !!python/tuple [128, 128]
  dataset: 'PIE_dataset'
  pretext_task: 'Shuffle'
  model: 'CONV3D'
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  path_dir_results: '/pub/experiments/jzafra/tuner_keras_results'
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters'
  epochs: 100
  n_frames: 16
  seed: 1
  num_classes: 2
  random: False
  tuners:
    tuner_1:
      type: 'Bayesian_Optimization'
      objetive: val_accuracy
      seed: 1
      num_initial_points: 5
      max_trials: 100
      project_name: '04092020-213100'
Shuffle:
  dim: !!python/tuple [128, 128]
  dataset: 'JAAD_dataset'
  model_name: 'CONV3D'
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  epochs: 100
  n_frames: 8
  seed: 1
  random: False
  tensorboard_logs: '/pub/experiments/jzafra/tensorboard'
  path_output_model: '/pub/experiments/jzafra/models'
  load_hyperparameters: False
  path_hyperparameters: '/pub/experiments/jzafra/hyperparameters/JAAD_dataset/Shuffle/Bayesian_Optimization/CONV3D/04092020-213445'
  hyperparameters:
    batch_size: 16
    dense_activation: 'relu'
    dropout_rate_1: 0.5
    dropout_rate_2: 0.5
    learning_rate: 0.0001
    normalized: true
    shuffle: true
    step_swaps: 1
    units: 512
Transfer_Learning:
  dataset: 'PIE_dataset'
  pretext_task: 'Shuffle'
  model_name: 'CONV3D'
  input_model:
  path_models: '/pub/experiments/jzafra/models'
  seed: 1
  random: False
  dim: !!python/tuple [128, 128]
  n_frames: 16
  channels: 3
  new_model_top:
    dropout_rate_1:
    dropout_rate_2:


