Keras_Tuner:
  dim: !!python/tuple [128, 128]
  dataset: 'JAAD_dataset'
  pretext_task: 'Shuffle'
  model: 'CONV3D'
  path_instances: '/pub/experiments/jzafra/instances/'
  path_id_instances: '/pub/experiments/jzafra/ids_instances/'
  path_dir_results: '/pub/experiments/jzafra/tuner_keras_results'
  epochs: 100
  n_frames: 8
  seed: 1
  num_classes: 2
  random: False
  tuners:
    tuner_1:
      type: 'Bayesian_Optimization'
      objetive: val_accuracy
      seed: 1
      num_initial_points: 5
      max_trials: 100
      directory: '/pub/experiments/jzafra/tuner_keras_results/JAAD_dataset/hypertuners/Bayesian_Optimization'
      project_name: 'CONV3D_model'
Shuffle:
  dim: !!python/tuple [128, 128]
  dataset: 'PIE_dataset'
  model_name: 'Conv3D'
  path_instances: '/media/jorge/DATOS/TFG/instances/'
  path_id_instances: '/media/jorge/DATOS/TFG/ids_instances/PIE/'
  batch_size:
  epochs:
  tensorboard_logs: '/media/jorge/DATOS/TFG/tensorboard_logs'
  path_output_models: '/media/jorge/DATOS/TFG/models'
  path_input_model:
  load_model: False
  model:
    dropout_rate_1:
    dropout_rate_2:
    dense_activation:
    units_dense_layer:
    learning_rate:


