Keras_Tuner:
  dim: !!python/tuple [128, 128]
  path_train_instances: /media/jorge/DATOS/TFG/ids_instances/PIE/train.txt
  path_validation_instances: /media/jorge/DATOS/TFG/ids_instances/PIE/validation.txt
  path_test_instances: /media/jorge/DATOS/TFG/ids_instances/PIE/test.txt
  epochs: 100
  n_frames: 16
  seed: 1
  num_classes: 2
  random: False
  Random_Search:
    objetive: val_accuracy
    seed: 1
    max_trials: 100
    executions_per_trial: 2
    directory: /media/jorge/DATOS/TFG/hypertuners/PIE_dataset/Random_Search
    project_name: CONV3D_model
  HyperBand:
    objetive: val_accuracy
    seed: 1
    max_epochs: 40
    executions_per_trial: 2
    directory: /media/jorge/DATOS/TFG/hypertuners/PIE_dataset/HyperBand
    project_name: CONV3D_model
  Bayesian_Optimization:
    objetive: val_accuracy
    seed: 1
    num_initial_points: 5
    max_trials: 100
    directory: /media/jorge/DATOS/TFG/hypertuners/PIE_dataset/Bayesian_Optimization
    project_name: CONV3D_model



